import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    width,
    height,
    position: 'relative',
    backgroundColor: 'pink',
  },
  wrapper: {
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '0%',
    bottom: '0%',
    backgroundColor: '#F5F5F5',
  },
  upperCont: {
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '-3.04%',
    bottom: '82.26%',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  upperWrapper: {
    width: '100%',
    height: height * 0.22,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  backIconWrapper: {
    width: width * 0.2,
    height: height * 0.05,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageWrapper: {
    width: width * 0.29,
    height: width * 0.15,
    display: 'flex',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 90,
  },
  uName: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  inputWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    left: '9.25%',
    right: '9.73%',
    top: '14.22%',
    bottom: '78.83%',
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: 20,
    elevation: 1,
    paddingLeft: 20,
  },
  boxCont1: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '8.03%',
    right: '8.1%',
    top: '14.22%',
    bottom: '24.5%',
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: 20,
    elevation: 2,
  },
  innerBox:{
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width:width*0.8,
    height:height*0.12,
    backgroundColor: '#f2f2f2',
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: 5,
    elevation: 2,
    margin:height*0.01,
    fontWeight: 'bold',
    flexDirection:'row',
  },
  tnc:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.035,
    color: '#5588e7',
  },

  circle: {
    width: width * 0.12,
    height: width * 0.12,
    borderRadius: width*0.12/2,
    borderColor: '#C7C7C7',
    borderWidth:1,
    margin:10,
    marginBottom:height*0.05,
    marginTop:height*0.045,
    //backgroundColor: '#5588e7',
  },

  name:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.035,
    color: 'black',
  },

  relation:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.035,
    color: '#9e9e9e',
  },

  age:{
    fontFamily: 'Helvetica Neue',
    fontSize: width * 0.035,
    color: 'black',
    marginTop: 10,
  },

  selectBtn: {
    width: '30%',
    backgroundColor: '#f2f2f2',
    borderRadius: 40,
    elevation: 1,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderColor: '#C7C7C7',
    borderWidth: 1,
    position: 'absolute',
    alignSelf:'center',
    marginHorizontal: width*0.2,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: height * 0.045,
    marginLeft: width * 0.5,
  },
  innerTextcont:{
    display: 'flex',
    flexDirection: 'column',
   },
  searchinp: {
    marginLeft: 12,
  },
  topText: {
    marginTop: height * 0.23,
  },
  texthead: {
    color: '#5588E7',
    marginLeft: 20,
    fontWeight: 'bold',
    fontSize: 16,
  },
  docListWrapper: {
    width,
    height: height * 0.8,
    backgroundColor: '#fff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: height * 0.2,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  docTypeWrapper: {
    width: width * 0.9,
    height: height * 0.1,
    borderBottomWidth: 1,
    borderBottomColor: '#7FE1D7',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textBox: {
    width: '70%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  labcatImg: {
    marginLeft: width * 0.02,
    width: width * 0.11,
    height: height * 0.05,
  },
  iconStyle: {
    marginRight: width * 0.02,
  },
  specialText: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'normal',
    color: '#000',
    fontSize: width * 0.04,
    marginLeft: width * 0.01,
  },
  bfbottomWrapper: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 40,
    padding: 20,
    elevation: 1,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderColor: '#C7C7C7',
    borderWidth: 1,
    position: 'absolute',
    bottom: 50,
    marginHorizontal: 12,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: height * 0.08,
    marginLeft: width * 0.045,
  },
  feedbackTextbtn: {
    fontSize: width * 0.04,
    fontWeight: 'bold',
    marginLeft: 18,
  },
  bookTextbtnWrapper: {
    width: '70%',
    padding: 10,
    borderRadius: 40,
    marginLeft: 40,
    height: height * 0.08,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookBtn: {
    width: '100%',
    borderRadius: 40,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookTextbtn: {
    fontWeight: 'bold',
    fontSize: width * 0.05,
    textAlign: 'center',
  },
  bottomBtnContainer: {
    position: 'absolute',
    right: 20,
    bottom: 25,
  },
  applyBtnContainer: {
    width: '100%',
    margin: 10,
    borderRadius: 40,
    padding: 15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    right: '67.5%',
  },
  btnText: {
    color: '#fff',
    fontSize: width * 0.042,
    fontWeight: '400',
  },
  titleWrapper: {
    width: width * 0.4,
    height: width * 0.15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  settingIconWrapper: {
    width: width * 0.22,
    height: height * 0.032,
    borderRadius: 50,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginLeft: width * 0.09,
    backgroundColor: '#ffffff',
  },
  dropName: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: width * 0.022,
    color: 'rgb(85,136,231)',
  },
});
