import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    width,
    height,
    position: 'relative',
    backgroundColor: 'pink',
  },
  wrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '0%',
    bottom: '0%',
    backgroundColor: '#F5F5F5',
  },
  upperCont: {
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '-3.4%',
    bottom: '78.54%',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  upperWrapper: {
    width: '100%',
    height: height * 0.22,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  backIconWrapper: {
    width: width * 0.2,
    height: height * 0.05,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleWrapper: {
    width: width * 0.4,
    height: width * 0.15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },

  filterWrapper: {
    width: width * 0.35,
    height: height * 0.15,
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: height * 0.03,
    backgroundColor: '#ffffff',
    padding:5,
  },
  filtertextBox: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    alignSelf:'flex-start',
  },
  filterWrapperText:{
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: width * 0.04,
    lineHeight: 25,
    color: '#fff',
  },

  uName: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: width * 0.04,
    lineHeight: 25,
    color: '#fff',
  },
  dropName: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: width * 0.022,
    color: 'rgb(85,136,231)',
  },
  catTypeWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    marginLeft: width*0.15,

  },
  catText: {
    backgroundColor: '#fff',
    marginHorizontal:5,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 20,
    marginTop: 1,
    fontWeight: '500',
  },

  docContWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '24%',
    bottom: '0%',
  },

  docCont: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '0%',
    bottom: '46%',
  },

  docDetailedWrapper: {
    width: width * 0.8,
    height: height * 0.39,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingBottom: 35,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: 20,
  },

  docDetailedWrapper2: {
    width: '10%',
    backgroundColor: '#fff',
    paddingBottom: 5,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },

  orderdetailswrap: {
    width: '10%',
    backgroundColor: '#fff',
    paddingBottom: 5,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  sponserWrapper: {
    width: '100%',
    height: height * 0.075,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  sponserText: {
    backgroundColor: '#fdf8e4',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    opacity: 0.8,
    marginTop: height * 0.02,
    fontSize: width * 0.032,
    fontWeight: 'bold',
    color: '#E6B12E',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  docSpecsWrapper: {
    width: '93%',
    display: 'flex',
    flexDirection: 'row',
  },
  pharmdetailImg: {
    width: width * 0.15,
    height: width * 0.11,
    marginLeft: width*0.025,
    marginTop: height*0.017,
    
    
  },
  perText: {
    fontFamily: 'Helvetica Neue',
    position: 'absolute',
    backgroundColor: '#62D248',
    color: '#fff',
    padding: 4,
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 30,
    fontSize: width * 0.028,
    fontWeight: 'normal',
    height: height * 0.05,
    textAlignVertical: 'center',
    top: '60%',
    left: '12%',
  },
  docNameWrapper: {
    width:width*0.35,
    marginLeft:width*0.015,
    display: 'flex',
    flexDirection: 'column',
    padding: 5,
    
  },
  docNameText: {
    fontFamily: 'Helvetica Neue',
    color: '#000',
    fontSize: width * 0.04,
    fontWeight: 'bold',
    paddingBottom: 1,
  },
  docSubNameText: {
    color: '#898A8F',
    fontSize: width * 0.025,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
  },
  docprofText: {
    color: '#898A8F',
    fontSize: width * 0.033,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
  },
  docExpText: {
    color: '#898A8F',
    fontSize: width * 0.033,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
  },
  middleWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: height * 0.01,
  },
  nodoctorWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  feedText: {
    fontSize: width * 0.0325,
    fontWeight: '700',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    marginLeft: width * 0.02,
  },
  nodocImg: {
    marginLeft: width * 0.028,
    width: 10.37,
    height:12,
  },
  doclocImg: {
    marginLeft: width * 0.028,
    height:12,
    width:12,
  },
  nodocText: {
    fontSize: width * 0.035,
    color: '#898A8F',
    marginLeft: width * 0.01,
  },
  doclocText: {
    marginLeft: width * 0.01,
    fontSize: width * 0.035,
    color: '#898A8F',
  },
  bottom1Wrapper: {
    width: '93%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: height * 0.015,
  },
  moreText: {
    fontSize: width * 0.032,
    borderWidth: 1,
    borderColor: '#8A9DA2',
    borderRadius: 20,
    paddingTop: 5,
    paddingBottom: 5,
    paddingRight: 5,
    paddingLeft: 5,
    textAlign: 'center',
    color: '#8A9DA2',
  },
  moneyWrapper: {
    width: width * 0.35,
    height: height * 0.048,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ecfbf9',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: 'rgba(1,1,1,1)',
    elevation: 2,
  },
  moneyText: {
    fontSize: width * 0.035,
    fontWeight: '400',
    color: '#000',
    marginLeft: width * 0.01,
  },
  bottom2Wrapper: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent:'space-evenly',
    alignItems: 'center',
  
  },
  boxBtn2: {
    width: width * 0.3,
    height: height * 0.05,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    marginRight: width * 0.018,
  },
  btnText: {
    fontWeight: 'bold',
  },

  docCont2: {
    width,
    height:height*0.68
  },

  docDetailedWrapper2: {
    width: width*0.9,
    height: height * 0.15,
    display: 'flex',
    flexDirection:'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginTop: height * 0.015,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: width*0.05,
  },

  filterBtnWrapper: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 12,
    width: width * 0.2,
    height: height * 0.12,
    marginBottom: 15,
  },

  filterBtnCont: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.2,
    height: width * 0.2,
    borderRadius: 50,
    elevation: 2,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    backgroundColor: '#ffffff',
  },
  filterImg:{
    height:26.49,
    width:22.66,
  },
  circle: {
    width: width * 0.20,
    height: width * 0.2,
    borderRadius: width*0.2/2,
    borderColor: '#5588e7',
    borderWidth:1,
    //backgroundColor: '#5588e7',
    alignSelf: 'center',
    marginLeft: width*0.02,
  },                             
  tnc:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.033,
    color: '#5588e7',
  },
  orderdetails:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.033,
    color: 'black',
  },
  bottomBtnContainer: {
    position: 'absolute',
    right: 50,
    bottom: 25,
  },
  applyBtnContainer: {
    width: '100%',
    margin: 10,
    borderRadius: 40,
    padding: 15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    right: '67.5%',
  },
  btnText: {
    color: '#fff',
    fontSize: width * 0.042,
    fontWeight: '400',
  },

  modalContentWrapper: {
    width: '70%',
    height: height * 0.05,
    display: 'flex',
    flexDirection:'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#7FE1D7',
  },
  modalWrapper:{
    backgroundColor:"#ffffff", 
    marginHorizontal:width*0.1,
    marginVertical:height*0.2,
    width:width*0.8,
    height:height*0.6,  
    padding:20, 
    borderRadius:20, 
    flex:1,
    //alignItems:'center',
  },
  modalBoxBtn: {
    width: width * 0.3,
    height: height * 0.05,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    marginRight: width * 0.018,

  },

  filterText:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.025,
    color: '#5588e7',
  },

  headerText:{
    fontFamily: 'Helvetica Neue',
  
    fontSize: width * 0.025,
    color: '#5588e7',
  },

  heading:{
    fontFamily: 'Helvetica Neue',
    fontSize: width * 0.06,
    fontWeight: "bold",
    color: '#5588e7',
  },

  dataText:{
    fontFamily: 'Helvetica Neue',

    fontSize: width * 0.025,
    color: '#000000',
  },
  settingIconWrapper: {
    width: width * 0.22,
    height: height * 0.032,
    borderRadius: 50,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginLeft: width * 0.09,
    backgroundColor: '#ffffff',
  },
  dropName: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: width * 0.022,
    color: 'rgb(85,136,231)',
  },
  centeredView: {
    alignSelf: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  modalView: {
    margin: 0,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5
  },

  modalDetailsView: {
    width:'100%',
    alignItems: "flex-start",
    marginTop: height*0.03,
  },

  modalFieldView: {
    width:'100%',
    alignItems: "flex-start",
    flexDirection: "row",
  },

  openButton: {
    backgroundColor: "#F194FF",
    borderRadius: 20,
    padding: 10,
    elevation: 2
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "left"
  },
  modalText: {
    marginBottom: 15,
    textAlign: "left"
  }, 
  patient_name:{
    alignContent:'flex-start', 
    fontSize:width*0.05,
  },
  patient_name_header:{
    fontWeight: "bold",
    alignContent:'flex-start', 
    fontSize:width*0.05,
  },
  applyBtnContainer: {
    width: '100%',
    margin: 10,
    borderRadius: 40,
    padding: 15,
    paddingHorizontal:width*0.2,
    justifyContent: 'center',
    alignItems:'center',
   
  },
  btnText: {
    color: '#fff',
    fontSize: width * 0.042,
    fontWeight: '400',
  },
}
);

