import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    width,
    height,
    position: 'relative',
    // backgroundColor: 'pink',
  },
  wrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '0%',
    bottom: '0%',
    backgroundColor: '#5588e7',
  },
  upperCont: {
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '-3.4%',
    bottom: '78.54%',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  upperWrapper: {
    width: '100%',
    height: height * 0.22,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  backIconWrapper: {
    width: width * 0.2,
    height: height * 0.05,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleWrapper: {
    width: width * 0.4,
    height: width * 0.15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },

  settingIconWrapper: {
    width: width * 0.22,
    height: height * 0.032,
    borderRadius: 50,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginLeft: width * 0.09,
    backgroundColor: '#ffffff',
  },
  uName: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: width * 0.05,
    lineHeight: 25,
    color: '#fff',
  },
  expandButton: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: width * 0.04,
    lineHeight: 25,
    color: '#fff',
    marginLeft:width*0.12
  },
  dropName: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: width * 0.022,
    color: 'rgb(85,136,231)',
  },
  catTypeWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    marginLeft: width*0.15,

  },
  catText: {
    backgroundColor: '#fff',
    marginHorizontal:5,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 20,
    marginTop: 1,
    fontWeight: '500',
  },

  docContWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '14%',
    bottom: '0%',
  },

  docCont: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '0%',
    bottom: '46%',
  },

  docDetailedWrapper: {
    width: width * 0.8,
    height: height * 0.39,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingBottom: 35,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: 20,
  },

  sponserWrapper: {
    width: '100%',
    height: height * 0.075,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  sponserText: {
    backgroundColor: '#fdf8e4',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    opacity: 0.8,
    marginTop: height * 0.02,
    fontSize: width * 0.032,
    fontWeight: 'bold',
    color: '#E6B12E',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  docSpecsWrapper: {
    width: '93%',
    display: 'flex',
    flexDirection: 'row',
  },
  pharmdetailImg: {
    width: width * 0.21,
    height: width * 0.15,
    marginLeft: width*0.025,
    marginTop: height*0.015,
    
    
  },
  perText: {
    fontFamily: 'Helvetica Neue',
    position: 'absolute',
    backgroundColor: '#62D248',
    color: '#fff',
    padding: 4,
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 30,
    fontSize: width * 0.028,
    fontWeight: 'normal',
    height: height * 0.05,
    textAlignVertical: 'center',
    top: '60%',
    left: '12%',
  },
  docNameWrapper: {
    marginLeft: 10,
    display: 'flex',
    flexDirection: 'column',
  },
  docNameText: {
    fontFamily: 'Helvetica Neue',
    color: '#000',
    fontSize: width * 0.04,
    fontWeight: 'bold',
    paddingBottom: 1,
  },
  docSubNameText: {
    color: '#898A8F',
    fontSize: width * 0.033,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
  },
  docprofText: {
    color: '#898A8F',
    fontSize: width * 0.033,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
  },
  docExpText: {
    color: '#898A8F',
    fontSize: width * 0.033,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
  },
  middleWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: height * 0.01,
  },
  nodoctorWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  feedText: {
    fontSize: width * 0.0325,
    fontWeight: '700',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    marginLeft: width * 0.02,
  },
  nodocImg: {
    marginLeft: width * 0.028,
    width: 10.37,
    height:12,
  },
  doclocImg: {
    marginLeft: width * 0.028,
    height:12,
    width:12,
  },
  nodocText: {
    fontSize: width * 0.035,
    color: '#898A8F',
    marginLeft: width * 0.01,
  },
  doclocText: {
    marginLeft: width * 0.01,
    fontSize: width * 0.035,
    color: '#898A8F',
  },
  bottom1Wrapper: {
    width: '93%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: height * 0.015,
  },
  moreText: {
    fontSize: width * 0.032,
    borderWidth: 1,
    borderColor: '#8A9DA2',
    borderRadius: 20,
    paddingTop: 5,
    paddingBottom: 5,
    paddingRight: 5,
    paddingLeft: 5,
    textAlign: 'center',
    color: '#8A9DA2',
  },
  moneyWrapper: {
    width: width * 0.35,
    height: height * 0.048,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ecfbf9',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: 'rgba(1,1,1,1)',
    elevation: 2,
  },
  moneyText: {
    fontSize: width * 0.035,
    fontWeight: '400',
    color: '#000',
    marginLeft: width * 0.01,
  },
  bottom2Wrapper: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent:'flex-start',
    alignItems: 'center',
    marginTop: height * 0.04,
    marginLeft: width *0.02,
  },
  boxBtn2: {
    width: width * 0.3,
    height: height * 0.05,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    marginRight: width * 0.018,
    marginTop: width*0.03,
  },
  btnText: {
    fontWeight: 'bold',
  },

  docCont2: {
    width,
    height:height*0.7,
  },

  docDetailedWrapper2: {
    width: width*0.9,
    height: height * 0.4,
    display: 'flex',
    flexDirection:'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginTop: height * 0.015,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: width*0.05,
  },
  proffsnDetailedWrapper: {
    width: width*0.9,
    height: height * 0.55,
    display: 'flex',
    flexDirection:'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginTop: height * 0.015,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: width*0.05,
  },
  proffsnDetailedWrapper2: {
    width: width*0.9,
    height: height * 0.5,
    display: 'flex',
    flexDirection:'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginTop: height * 0.015,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: width*0.05,
    marginBottom:height * 0.2,
  },
  proffsnDetailedWrapper3: {
    width: width*0.9,
    height: height * 0.6,
    display: 'flex',
    flexDirection:'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginTop: height * 0.015,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: width*0.05,
    marginBottom:height * 0.3,
    
  },
  pastDetailedWrapper: {
    width: width*0.9,
    height: height * 0.4,
    display: 'flex',
    flexDirection:'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginTop: -(height * 0.1),
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: width*0.05,
  },

 

  docDetailedWrapper3: {
    width: width*0.9,
    height: height * 0.5,
    display: 'flex',
    flexDirection:'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginTop: height * 0.02,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    marginLeft: width*0.05,
    marginBottom: height*0.05,
  },

  filterBtnWrapper: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 12,
    width: width * 0.2,
    height: height * 0.12,
    marginBottom: 15,
  },

  filterBtnCont: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.2,
    height: width * 0.2,
    borderRadius: 50,
    elevation: 2,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    backgroundColor: '#ffffff',
  },
  circle: {
    width: width * 0.06,
    height: width * 0.06,
    borderRadius: width*0.06/2,
    borderColor: '#5588e7',
    borderWidth:1,
    alignSelf: 'center',
    marginLeft: width*0.02,
    backgroundColor: '#5588e7',
  },                             
  tnc:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.033,
    color: '#5588e7',
  },
  orderdetails:{
    fontFamily: 'Helvetica Neue',
    fontWeight: 'bold',
    fontSize: width * 0.033,
    color: 'black',
  },
  bottomBtnContainer: {
    position: 'absolute',
    right: 50,
    bottom: 25,
  },
  applyBtnContainer: {
    width: '100%',
    margin: 10,
    borderRadius: 40,
    padding: 15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    right: '67.5%',
  },
  btnText: {
    color: '#fff',
    fontSize: width * 0.042,
    fontWeight: '400',
  },
  innerBox1:{
    display:'flex',
    flexDirection:'row',
    borderBottomWidth: 1,
    borderBottomColor: '#7FE1D7',
    width:'90%',
    height:'40%',
  },
  innerBox2:{
    display:'flex',
    flexDirection:'row',
    width:'90%',
    height:'40%',
  },
  imagebox:{
    display:'flex',
    flexDirection:'column',
    width:'15%',
    height:'90%',
  },
  time:{
    alignSelf:'flex-start',
    marginLeft: width*0.1,
    color:'#898A8F',
    fontWeight:'bold',
  },
  docImage:{
    alignSelf:'center',
    marginTop: height*0.01,
  },
  textBox:{
    display:'flex',
    flexDirection:'column',
    width:'85%',
    height:'90%',
  },
  checkBox:{
    display:'flex',
    flexDirection:'column',
    width:'25%',
    height:'90%',
    alignItems:'flex-end',
  },
  vaccineName:{
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: width * 0.039,
    marginLeft:width*0.03,
  },
  doctorName:{
    marginTop: height*0.021,
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontSize: width * 0.039,
  },
  date:{
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontSize: width * 0.035,
    position:'absolute',
    left: width*0.5,

  },
  check:{
    marginTop:height*0.01,
  },

  paraAns:{
    width: '90%',
    height: '70%',
    margin:10,
    backgroundColor: '#f2f2f2',
    paddingBottom: 5,
    borderRadius: 15,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    // justifyContent:'flex-start',
    // alignItems:'flex-start',
    textAlignVertical: 'top'
  },

  answers:{
    width: '78%',
    height: '13%',
    backgroundColor: '#f2f2f2',
    borderRadius: 5,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    fontSize:height*0.015,
    marginLeft:width*0.05,
    marginTop:height*0.01,
    justifyContent:'center',
    alignItems:'center'
  },
  answers1:{
    width: '78%',
    height: '10%',
    backgroundColor: '#f2f2f2',
    borderRadius: 5,
    shadowColor: 'rgba(1, 1, 1, 1)',
    elevation: 4,
    fontSize:height*0.015,
    marginLeft:width*0.05,
    marginTop:height*0.01
  },

  disease:{
    marginTop:'5%',
    display:'flex',
    flexDirection:'row',
    width:'90%',
    height:'10%',
    alignItems: 'center',

  },
  symptomText:{
    marginTop:'5%',
    display:'flex',
    flexDirection:'row',
    width:'90%',
    height:'5%',
    alignItems: 'center',

  },
  circleQ: {
    width: width * 0.06,
    height: width * 0.06,
    borderRadius: width*0.06/2,
    borderColor: '#5588e7',
    borderWidth:1,
    alignSelf: 'center',
    marginTop: height*0.015,
  
  },           
  QText:{
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: width * 0.039,
    marginTop: height*0.015,
  },

  bfbottomWrapper: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 40,
    padding: 20,
    elevation: 1,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderColor: '#C7C7C7',
    borderWidth: 1,
    position: 'absolute',
    bottom: 35,
    marginHorizontal: 12,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: height * 0.08,
    marginLeft: width * 0.045,
  },
  feedbackTextbtn: {
    fontSize: width * 0.04,
    fontWeight: 'bold',
    marginLeft: 60,
  },
  bookTextbtnWrapper: {
    width: '65%',
    padding: 10,
    borderRadius: 40,
    marginLeft: 40,
    height: height * 0.08,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookBtn: {
    width: '100%',
    borderRadius: 40,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookTextbtn: {
    fontWeight: 'bold',
    fontSize: width * 0.05,
    textAlign: 'center',
  },
  selectMultiple:{
    position:'relative',
    flex:1,
    left:5,
  },
    innerBox:{
      display: 'flex',
      justifyContent:'center',
      //alignItems: 'center',
      width:'100%',
      height:'100%',
      backgroundColor: '#f2f2f2',
      shadowColor: 'rgba(0, 0, 0, 0.25)',
      borderRadius: 5,
      elevation: 2,
      margin: height*0.01,
      fontWeight: 'bold',
      fontSize:height*0.020,
      paddingVertical: 0,
      paddingHorizontal: 15,
    
    
      
    },
    
  
    innerBoxWrapper:{
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width:width*0.74,
      height:height*0.060,
      backgroundColor: '#f2f2f2',
      shadowColor: 'rgba(0, 0, 0, 0.25)',
      borderRadius: 5,
      elevation: 2,
      margin: height*0.01,
      // marginTop:height*0.01,
      fontWeight: 'bold',
      fontSize:height*0.015,
      // paddingTop:height*0.01
     
    },
  
  }





);


